spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam
    username: root
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
      format_sql: true